import { Injectable } from "@nestjs/common";
import { Database } from "../database/database";
import { AllocationService } from "../inventory/allocation.service";
import { DeliveryConfigService } from "../delivery-config/delivery-config.service";
import { ApiProblem } from "../http/errors";
import { PaymentPolicyService } from "../payments/payment-policy.service";
const blockedFulfilment=new Set(["dispatched","delivered","collected"]);
const capturedPayment=new Set(["succeeded","partially_refunded","refund_pending","refunded","requires_review"]);
@Injectable()
export class OrderCancellationService {
  constructor(private readonly db:Database,private readonly allocation:AllocationService,private readonly delivery:DeliveryConfigService,private readonly payments:PaymentPolicyService){}
  async cancel(userId:string,requestId:string,orderId:string,reason:string){const normalized=reason.trim().replace(/\s+/g," ");if(!normalized)throw new ApiProblem(400,"VALIDATION_FAILED","Cancellation reason is required.");return this.db.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "Order" WHERE id=${orderId} FOR UPDATE`;const order=await tx.order.findUnique({where:{id:orderId}});if(!order||order.customerUserId!==userId)throw new ApiProblem(404,"NOT_FOUND","Order not found.");if(order.fulfilmentStatus==="cancelled"){if(order.cancelledReason===normalized)return{fulfilmentStatus:"cancelled"};throw new ApiProblem(409,"CONFLICT","Order was already cancelled with a different reason.");}if(capturedPayment.has(order.paymentStatus))throw new ApiProblem(422,"RULE_VIOLATION","This order requires the refund workflow before cancellation.");await this.payments.assertCancellationSafe(tx,orderId);if(order.stockConsumedAt||blockedFulfilment.has(order.fulfilmentStatus))throw new ApiProblem(409,"CONFLICT","Order can no longer be cancelled before handover.");await tx.order.update({where:{id:orderId},data:{fulfilmentStatus:"cancelled",cancelledAt:new Date(),cancelledReason:normalized,version:{increment:1}}});const context={actorId:userId,requestId};await this.allocation.release(tx,"order",orderId,context);await this.delivery.releaseBooking(tx,orderId,context);await tx.orderEvent.create({data:{orderId,actorKind:"customer",actorId:userId,action:"order.cancelled",fromStatus:order.fulfilmentStatus,toStatus:"cancelled",note:normalized,customerSafe:true}});await tx.auditEvent.create({data:{actorId:userId,action:"order.cancelled",entityId:orderId,requestId,details:{reason:normalized}}});await tx.outboxEvent.create({data:{type:"order.cancelled",aggregateId:orderId,payload:{orderId,reason:normalized}}});return{fulfilmentStatus:"cancelled"};},{timeout:15000});}
}
