import { after, before, beforeEach, test } from "node:test";
import assert from "node:assert/strict";
import type { INestApplication } from "@nestjs/common";
import { createApplication } from "../src/bootstrap";
import { Database } from "../src/database/database";
import { commerceTestPassword, seedCommerceFixtures } from "./commerce-fixtures";

let app: INestApplication; let db: Database; let base: string;
const collectionBody = (quantity="1") => ({lines:[{variantId:"var-rice",quantity}],customerName:"Ama",customerPhone:"+233241111111",fulfilment:"collection",paymentMethod:"cash_counter"});
async function post(path:string,body:unknown,headers:Record<string,string>={}) { const r=await fetch(base+"/api/v1"+path,{method:"POST",headers:{"content-type":"application/json",...headers},body:JSON.stringify(body)}); return {r,body:await r.json()}; }
async function native(email:string){ const x=await post("/auth/sessions",{email,password:commerceTestPassword,client:"native"},{origin:"http://localhost:3000"}); assert.equal(x.r.status,201); return x.body.data.accessToken as string; }
async function guest(){ const q=await post("/checkout/quote",{lines:[{variantId:"var-rice",quantity:"1"}]}); assert.equal(q.r.status,200); const cookies=(q.r.headers as any).getSetCookie?.()??[q.r.headers.get("set-cookie")]; const cookie=cookies.filter(Boolean).map((x:string)=>x.split(";")[0]).join("; "); const csrf=/vg_guest_csrf=([^;]+)/.exec(cookie)?.[1]; assert.ok(csrf); return {cookie,csrf}; }
async function complete(body:any,key:string,headers:Record<string,string>={}) { return post("/checkout/complete",body,{origin:"http://localhost:3000","idempotency-key":key,...headers}); }
before(async()=>{app=await createApplication();await app.listen(0,"127.0.0.1");base=await app.getUrl();db=app.get(Database);}); beforeEach(async()=>{await seedCommerceFixtures(db);}); after(async()=>{await app.close();});

test("first guest complete bootstraps capability but creates no commerce state",async()=>{const x=await complete(collectionBody(),"guest-first-1"); assert.equal(x.r.status,403); assert.match(x.r.headers.get("set-cookie")??"",/vg_guest=/); assert.deepEqual(await Promise.all([db.order.count(),db.reservation.count(),db.deliverySlotBooking.count(),db.idempotency.count()]),[0,0,0,0]);});

test("guest checkout atomically snapshots lines reserves stock and replays without secret persistence",async()=>{const g=await guest(); const h={cookie:g.cookie,"x-csrf-token":g.csrf}; const x=await complete(collectionBody("1.005"),"guest-replay-1",h); assert.equal(x.r.status,201); assert.match(x.body.data.verificationCode,/^[0-9A-HJKMNP-TV-Z]{10}$/); const order=await db.order.findUniqueOrThrow({where:{id:x.body.data.orderId},include:{lines:true}}); assert.equal(order.guestSessionId!==null,true); assert.equal(order.subtotalMinor,200); assert.equal(order.paymentStatus,"unpaid"); assert.equal(order.lines[0].unitPriceMinor,199); const holds=await db.reservation.findMany({where:{claimId:order.id,state:"active"}}); assert.ok(holds.length>=1); assert.equal(new Set(holds.map(r=>r.expiresAt.toISOString())).size,1); const replay=await complete(collectionBody("1.005"),"guest-replay-1",h); assert.equal(replay.r.status,201); assert.deepEqual(replay.body.data,x.body.data); assert.equal(await db.order.count(),1); const idem=await db.idempotency.findFirstOrThrow(); const persisted=JSON.stringify(idem.outcome); assert.ok(!persisted.includes(x.body.data.verificationCode)); assert.ok(!persisted.includes(g.csrf)); const changed=await complete(collectionBody("2"),"guest-replay-1",h); assert.equal(changed.r.status,409);});

test("authenticated delivery checkout owns address books slot and preserves policy/status dimensions",async()=>{const token=await native("customer-a@example.test"); const body={lines:[{variantId:"var-rice",quantity:"6"}],customerName:"Ama",customerPhone:"+233241111111",customerId:"customer-a",fulfilment:"delivery",zoneId:"zone-required",slotId:"slot-future",addressId:"address-a",paymentMethod:"cash_on_delivery"}; const x=await complete(body,"customer-delivery-1",{authorization:"Bearer "+token}); assert.equal(x.r.status,201); assert.equal(x.body.data.paymentRequired,false); const order=await db.order.findUniqueOrThrow({where:{id:x.body.data.orderId},include:{deliveryAddress:true,slotBooking:true}}); assert.equal(order.customerUserId,"customer-a"); assert.equal(order.deliveryAddress?.street,"A Street"); assert.equal(order.slotBooking?.state,"active"); assert.equal(order.paymentStatus,"unpaid"); assert.equal(await db.auditEvent.count({where:{entityId:order.id}})>=3,true); assert.equal(await db.outboxEvent.count({where:{aggregateId:order.id}})>=3,true);});

test("checkout rejects forged ownership and invalid fulfilment payment slot policy without partial effects",async()=>{const token=await native("customer-a@example.test"); const auth={authorization:"Bearer "+token}; const cases:[any,number][]=[
[{...collectionBody(),customerId:"customer-b"},403],
[{...collectionBody(),fulfilment:"delivery",paymentMethod:"cash_counter",zoneId:"zone-required",slotId:"slot-future",addressId:"address-a"},400],
[{...collectionBody(),paymentMethod:"cash_on_delivery"},400],
[{...collectionBody(),fulfilment:"delivery",paymentMethod:"mobile_money",zoneId:"zone-required",addressId:"address-a"},400],
[{...collectionBody(),fulfilment:"delivery",paymentMethod:"mobile_money",zoneId:"zone-none",slotId:"slot-future",addressId:"address-a"},400],
[{...collectionBody(),fulfilment:"delivery",paymentMethod:"mobile_money",zoneId:"zone-optional",addressId:"address-b"},403],
]; let i=0; for(const [body,status] of cases){const x=await complete(body,"invalid-case-"+(i++),auth);assert.equal(x.r.status,status);} assert.equal(await db.order.count(),0); assert.equal(await db.reservation.count(),0); assert.equal(await db.idempotency.count(),0);});

test("two customer scopes racing final stock produce exactly one durable order",async()=>{await db.stockLot.update({where:{id:"lot-salt"},data:{quantity:"1"}}); const [a,b]=await Promise.all([native("customer-a@example.test"),native("customer-b@example.test")]); const body=(name:string)=>({lines:[{variantId:"var-salt",quantity:"1"}],customerName:name,customerPhone:"+233241111111",fulfilment:"collection",paymentMethod:"cash_counter"}); const rs=await Promise.all([complete(body("A"),"final-stock-a",{authorization:"Bearer "+a}),complete(body("B"),"final-stock-b",{authorization:"Bearer "+b})]); assert.deepEqual(rs.map(x=>x.r.status).sort(),[201,409]); assert.equal(await db.order.count(),1); assert.equal(await db.reservation.count({where:{state:"active"}}),1);});

test("multi-line stock failure and order outbox failure roll back the whole checkout transaction",async()=>{const token=await native("customer-a@example.test"); const auth={authorization:"Bearer "+token}; const bad={...collectionBody(),lines:[{variantId:"var-rice",quantity:"1"},{variantId:"var-salt",quantity:"99"}]}; const a=await complete(bad,"rollback-stock",auth); assert.equal(a.r.status,409); assert.deepEqual(await Promise.all([db.order.count(),db.reservation.count(),db.idempotency.count()]),[0,0,0]); await db.$executeRawUnsafe(`CREATE FUNCTION reject_order_created() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.type='order.created' THEN RAISE EXCEPTION 'order outbox fault'; END IF; RETURN NEW; END; $$`); await db.$executeRawUnsafe(`CREATE TRIGGER reject_order_created BEFORE INSERT ON "OutboxEvent" FOR EACH ROW EXECUTE FUNCTION reject_order_created()`); try { const b=await complete(collectionBody(),"rollback-outbox",auth); assert.equal(b.r.status,500); assert.deepEqual(await Promise.all([db.order.count(),db.reservation.count(),db.idempotency.count()]),[0,0,0]); } finally { await db.$executeRawUnsafe(`DROP TRIGGER reject_order_created ON "OutboxEvent"`); await db.$executeRawUnsafe(`DROP FUNCTION reject_order_created()`); }});

test("same actor and key races replay one order while key scopes remain independent",async()=>{const a=await native("customer-a@example.test"); const body=collectionBody(); const h={authorization:"Bearer "+a}; const rs=await Promise.all([complete(body,"same-key-race",h),complete(body,"same-key-race",h)]); assert.deepEqual(rs.map(x=>x.r.status),[201,201]); assert.deepEqual(rs[0].body.data,rs[1].body.data); assert.equal(await db.order.count(),1); const b=await native("customer-b@example.test"); const other=await complete({...body,customerName:"Kojo"},"same-key-race",{authorization:"Bearer "+b}); assert.equal(other.r.status,201); assert.equal(await db.order.count(),2);});

test("REST replay header is authoritative and valid electronic delivery policies fail closed without a provider",async()=>{const token=await native("customer-a@example.test"); const auth={authorization:"Bearer "+token}; const mismatch=await post("/checkout/complete",{...collectionBody(),idempotencyKey:"body-key-123"},{origin:"http://localhost:3000","idempotency-key":"header-key-123",...auth}); assert.equal(mismatch.r.status,409); for(const [zone,address,key] of [["zone-optional","address-a","optional-no-slot"],["zone-none","address-a","none-no-slot"]] as const){const x=await complete({...collectionBody(),fulfilment:"delivery",paymentMethod:"mobile_money",zoneId:zone,addressId:address},key,auth); assert.equal(x.r.status,503); assert.equal(x.body.error.code,"UNAVAILABLE");} assert.equal(await db.order.count(),0);});

test("order audit failure rolls back order lines holds and replay record",async()=>{const token=await native("customer-a@example.test"); await db.$executeRawUnsafe(`CREATE FUNCTION reject_order_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.action='order.created' THEN RAISE EXCEPTION 'order audit fault'; END IF; RETURN NEW; END; $$`); await db.$executeRawUnsafe(`CREATE TRIGGER reject_order_audit BEFORE INSERT ON "AuditEvent" FOR EACH ROW EXECUTE FUNCTION reject_order_audit()`); try {const x=await complete(collectionBody(),"rollback-audit",{authorization:"Bearer "+token}); assert.equal(x.r.status,500); assert.deepEqual(await Promise.all([db.order.count(),db.orderLine.count(),db.reservation.count(),db.idempotency.count()]),[0,0,0,0]);} finally {await db.$executeRawUnsafe(`DROP TRIGGER reject_order_audit ON "AuditEvent"`); await db.$executeRawUnsafe(`DROP FUNCTION reject_order_audit()`);} });

test("checkout fails closed when the configured commerce stock location becomes inactive",async()=>{
  const token=await native("customer-a@example.test"); await db.location.update({where:{id:"loc_accra"},data:{active:false}});
  const x=await complete(collectionBody(),"closed-location",{authorization:"Bearer "+token});
  assert.equal(x.r.status,503); assert.equal(x.body.error.code,"UNAVAILABLE");
  assert.deepEqual(await Promise.all([db.order.count(),db.reservation.count(),db.idempotency.count()]),[0,0,0]);
});
