import { after,before,beforeEach,test } from "node:test";
import assert from "node:assert/strict";
import type { INestApplication } from "@nestjs/common";
import { createApplication } from "../src/bootstrap";
import { Database } from "../src/database/database";
import { readConfig } from "../src/config";
import { commerceTestPassword,seedCommerceFixtures } from "./commerce-fixtures";
let app:INestApplication,second:INestApplication,db:Database; let base:string,secondBase:string;
async function post(url:string,path:string,body:any,headers:Record<string,string>={}){const r=await fetch(url+"/api/v1"+path,{method:"POST",headers:{"content-type":"application/json",...headers},body:JSON.stringify(body)});return{r,body:await r.json()};}
async function get(url:string,path:string,headers:Record<string,string>={}){const r=await fetch(url+"/api/v1"+path,{headers});return{r,body:await r.json()};}
async function native(email:string){const x=await post(base,"/auth/sessions",{email,password:commerceTestPassword,client:"native"},{origin:"http://localhost:3000"});assert.equal(x.r.status,201);return x.body.data.accessToken as string;}
async function guest(){const q=await post(base,"/checkout/quote",{lines:[{variantId:"var-rice",quantity:"1"}]});const cookies=(q.r.headers as any).getSetCookie?.()??[q.r.headers.get("set-cookie")];const cookie=cookies.filter(Boolean).map((x:string)=>x.split(";")[0]).join("; ");const csrf=/vg_guest_csrf=([^;]+)/.exec(cookie)?.[1]!;return{cookie,csrf};}
async function complete(headers:Record<string,string>,key:string,name="Ama"){return post(base,"/checkout/complete",{lines:[{variantId:"var-rice",quantity:"1"}],customerName:name,customerPhone:"+233241111111",fulfilment:"collection",paymentMethod:"cash_counter"},{origin:"http://localhost:3000","idempotency-key":key,...headers});}
before(async()=>{app=await createApplication();second=await createApplication();await app.listen(0,"127.0.0.1");await second.listen(0,"127.0.0.1");base=await app.getUrl();secondBase=await second.getUrl();db=app.get(Database);}); beforeEach(async()=>{await seedCommerceFixtures(db);}); after(async()=>{await second.close();await app.close();});

test("guest and customer order status is owner-only and guessed ids reveal nothing",async()=>{const ga=await guest();const a=await complete({cookie:ga.cookie,"x-csrf-token":ga.csrf},"guest-a-read");const gb=await guest();assert.equal((await get(base,"/orders/"+a.body.data.orderId,{cookie:gb.cookie})).r.status,404);assert.equal((await get(base,"/orders/"+a.body.data.orderId)).r.status,401);const ta=await native("customer-a@example.test"),tb=await native("customer-b@example.test");const ca=await complete({authorization:"Bearer "+ta},"customer-a-read");assert.equal((await get(base,"/orders/"+ca.body.data.orderId,{authorization:"Bearer "+tb})).r.status,404);assert.equal((await get(base,"/orders/not-a-real-order",{authorization:"Bearer "+ta})).r.status,404);});

test("customer list is bounded to authenticated owner and compatibility customerId cannot grant authority",async()=>{const a=await native("customer-a@example.test"),b=await native("customer-b@example.test");await complete({authorization:"Bearer "+a},"list-a-001");await complete({authorization:"Bearer "+b},"list-b-001","Kojo");const own=await get(base,"/account/orders?customerId=customer-a&page=1&perPage=10",{authorization:"Bearer "+a});assert.equal(own.r.status,200);assert.equal(own.body.data.length,1);assert.equal(own.body.data[0].lineCount,1);assert.equal((await get(base,"/account/orders?customerId=customer-b",{authorization:"Bearer "+a})).r.status,403);const admin=await native("admin-commerce@example.test");assert.equal((await get(base,"/account/orders",{authorization:"Bearer "+admin})).r.status,403);});

test("public projection never exposes stock lots verification secrets or fabricated subsystems",async()=>{const a=await native("customer-a@example.test");const x=await complete({authorization:"Bearer "+a},"projection-a");const r=await get(base,"/orders/"+x.body.data.orderId,{authorization:"Bearer "+a});assert.equal(r.r.status,200);assert.equal(r.body.data.verificationCode,undefined);assert.deepEqual(r.body.data.paymentAttempts,[]);assert.deepEqual(r.body.data.returns,[]);assert.deepEqual(r.body.data.notes,[]);assert.equal(r.body.data.job,undefined);assert.deepEqual(r.body.data.lines[0].allocations,[]);const text=JSON.stringify(r.body.data);assert.ok(!text.includes("lot-rice"));assert.ok(!text.includes("verificationCodeHash"));assert.ok(!text.includes("AuditEvent"));});

test("expired guest capability immediately loses order ownership",async()=>{const g=await guest();const x=await complete({cookie:g.cookie,"x-csrf-token":g.csrf},"guest-expire");const order=await db.order.findUniqueOrThrow({where:{id:x.body.data.orderId}});await db.guestCheckoutSession.update({where:{id:order.guestSessionId!},data:{expiresAt:new Date(0)}});assert.equal((await get(base,"/orders/"+order.id,{cookie:g.cookie})).r.status,401);});

test("tracking accepts reference plus code while wrong reference and code are indistinguishable and secret-free",async()=>{const a=await native("customer-a@example.test");const x=await complete({authorization:"Bearer "+a},"track-good");const good=await post(base,"/orders/track",{reference:x.body.data.reference,code:x.body.data.verificationCode});assert.equal(good.r.status,200);assert.equal(good.body.data.id,x.body.data.orderId);const wrong1=await post(base,"/orders/track",{reference:"VG-NOT-THERE",code:"0000000000"});const wrong2=await post(base,"/orders/track",{reference:x.body.data.reference,code:"0000000000"});assert.equal(wrong1.r.status,403);assert.equal(wrong2.r.status,403);assert.deepEqual(wrong1.body.error,wrong2.body.error);const stored=JSON.stringify(await db.trackingThrottle.findMany())+JSON.stringify(await db.auditEvent.findMany({where:{action:"security.order_track_failed"}}));assert.ok(!stored.includes("0000000000"));assert.ok(!stored.includes(x.body.data.verificationCode));});

test("tracking failure limit is durable across API instances",async()=>{for(let i=0;i<5;i++){const x=await post(i%2?secondBase:base,"/orders/track",{reference:"VG-RATE-LIMIT",code:"0000000000"});assert.equal(x.r.status,403);}const blocked=await post(secondBase,"/orders/track",{reference:"VG-RATE-LIMIT",code:"0000000000"});assert.equal(blocked.r.status,429);});

test("orders created under retained verification key remain trackable after active-key rotation",async()=>{const a=await native("customer-a@example.test");const x=await complete({authorization:"Bearer "+a},"rotation-order");const e={...process.env,ORDER_VERIFICATION_ACTIVE_VERSION:"2",ORDER_VERIFICATION_KEYS:JSON.stringify({1:"11".repeat(32),2:"22".repeat(32)})};const rotated=await createApplication(readConfig(e));await rotated.listen(0,"127.0.0.1");try{const u=await rotated.getUrl();const tracked=await post(u,"/orders/track",{reference:x.body.data.reference,code:x.body.data.verificationCode});assert.equal(tracked.r.status,200);}finally{await rotated.close();}});
