import { after,before,beforeEach,test } from "node:test";
import assert from "node:assert/strict";
import type { INestApplication } from "@nestjs/common";
import { createApplication } from "../src/bootstrap";
import { Database } from "../src/database/database";
import { commerceTestPassword,seedCommerceFixtures } from "./commerce-fixtures";
let app:INestApplication,db:Database,base:string;
async function post(path:string,body:any,headers:Record<string,string>={}){const r=await fetch(base+"/api/v1"+path,{method:"POST",headers:{"content-type":"application/json",...headers},body:JSON.stringify(body)});return{r,body:await r.json()};}
async function native(email:string){const x=await post("/auth/sessions",{email,password:commerceTestPassword,client:"native"},{origin:"http://localhost:3000"});assert.equal(x.r.status,201);return x.body.data.accessToken as string;}
async function complete(token:string,key:string,delivery=false){const body:any={lines:[{variantId:"var-rice",quantity:delivery?"6":"1"}],customerName:"Ama",customerPhone:"+233241111111",fulfilment:delivery?"delivery":"collection",paymentMethod:delivery?"cash_on_delivery":"cash_counter"};if(delivery)Object.assign(body,{zoneId:"zone-required",slotId:"slot-future",addressId:"address-a"});const x=await post("/checkout/complete",body,{authorization:"Bearer "+token,origin:"http://localhost:3000","idempotency-key":key});assert.equal(x.r.status,201);return x.body.data;}
async function cancel(token:string,id:string,reason="Changed mind",compat?:string){return post(`/account/orders/${id}/cancel`,{reason,...(compat?{orderId:compat}:{})},{authorization:"Bearer "+token,origin:"http://localhost:3000"});}
before(async()=>{app=await createApplication();await app.listen(0,"127.0.0.1");base=await app.getUrl();db=app.get(Database);});beforeEach(async()=>{await seedCommerceFixtures(db);});after(async()=>{await app.close();});

test("eligible customer cancellation releases stock and slot exactly once",async()=>{const a=await native("customer-a@example.test");const o=await complete(a,"cancel-delivery-001",true);const first=await cancel(a,o.orderId," No longer needed ");assert.equal(first.r.status,200);assert.equal(first.body.data.fulfilmentStatus,"cancelled");assert.equal(await db.reservation.count({where:{claimId:o.orderId,state:"active"}}),0);assert.equal((await db.deliverySlotBooking.findUniqueOrThrow({where:{orderId:o.orderId}})).state,"released");const events=await db.orderEvent.count({where:{orderId:o.orderId,action:"order.cancelled"}});const again=await cancel(a,o.orderId,"No longer needed");assert.equal(again.r.status,200);assert.equal(await db.orderEvent.count({where:{orderId:o.orderId,action:"order.cancelled"}}),events);assert.equal((await cancel(a,o.orderId,"Different reason")).r.status,409);});

test("guest admin and another customer cannot cancel a customer order or forge path ownership",async()=>{const a=await native("customer-a@example.test"),b=await native("customer-b@example.test"),admin=await native("admin-commerce@example.test");const o=await complete(a,"cancel-owner-001");assert.equal((await cancel(b,o.orderId)).r.status,404);assert.equal((await cancel(admin,o.orderId)).r.status,403);assert.equal((await post(`/account/orders/${o.orderId}/cancel`,{reason:"x"})).r.status,401);assert.equal((await cancel(a,o.orderId,"x","another-order")).r.status,400);});

test("handover and terminal fulfilment states refuse cancellation without releasing stock",async()=>{const a=await native("customer-a@example.test");for(const state of ["dispatched","delivered","collected"]){const o=await complete(a,`protected-${state}`);await db.order.update({where:{id:o.orderId},data:{fulfilmentStatus:state}});assert.equal((await cancel(a,o.orderId)).r.status,409);assert.ok(await db.reservation.count({where:{claimId:o.orderId,state:"active"}}));}const o=await complete(a,"protected-consumed");await db.order.update({where:{id:o.orderId},data:{stockConsumedAt:new Date()}});assert.equal((await cancel(a,o.orderId)).r.status,409);});

test("captured or refund-sensitive payment states require refund workflow while pre-capture states remain cancellable",async()=>{const a=await native("customer-a@example.test");for(const status of ["succeeded","partially_refunded","refund_pending","refunded","requires_review"]){const o=await complete(a,`paid-${status.replaceAll("_","")}`);await db.order.update({where:{id:o.orderId},data:{paymentStatus:status}});assert.equal((await cancel(a,o.orderId)).r.status,422);assert.ok(await db.reservation.count({where:{claimId:o.orderId,state:"active"}}));}for(const status of ["pending","failed","expired"]){const o=await complete(a,`precap-${status}`);await db.order.update({where:{id:o.orderId},data:{paymentStatus:status}});assert.equal((await cancel(a,o.orderId)).r.status,200);}});

test("cancellation outbox failure rolls back order reservation slot and event changes",async()=>{const a=await native("customer-a@example.test");const o=await complete(a,"cancel-rollback-001",true);await db.$executeRawUnsafe(`CREATE FUNCTION reject_cancel_outbox() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.type='order.cancelled' THEN RAISE EXCEPTION 'cancel outbox fault'; END IF; RETURN NEW; END; $$`);await db.$executeRawUnsafe(`CREATE TRIGGER reject_cancel_outbox BEFORE INSERT ON "OutboxEvent" FOR EACH ROW EXECUTE FUNCTION reject_cancel_outbox()`);try{assert.equal((await cancel(a,o.orderId)).r.status,500);const order=await db.order.findUniqueOrThrow({where:{id:o.orderId}});assert.notEqual(order.fulfilmentStatus,"cancelled");assert.ok(await db.reservation.count({where:{claimId:o.orderId,state:"active"}}));assert.equal((await db.deliverySlotBooking.findUniqueOrThrow({where:{orderId:o.orderId}})).state,"active");assert.equal(await db.orderEvent.count({where:{orderId:o.orderId,action:"order.cancelled"}}),0);}finally{await db.$executeRawUnsafe(`DROP TRIGGER reject_cancel_outbox ON "OutboxEvent"`);await db.$executeRawUnsafe(`DROP FUNCTION reject_cancel_outbox()`);}});

test("row lock makes cancellation observe a competing dispatch transition",async()=>{const a=await native("customer-a@example.test");const o=await complete(a,"cancel-race-001");let unlock!:()=>void;const hold=new Promise<void>(r=>unlock=r);let locked!:()=>void;const ready=new Promise<void>(r=>locked=r);const transition=db.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "Order" WHERE id=${o.orderId} FOR UPDATE`;locked();await hold;await tx.order.update({where:{id:o.orderId},data:{fulfilmentStatus:"dispatched"}});});await ready;const attempt=cancel(a,o.orderId);unlock();await transition;assert.equal((await attempt).r.status,409);assert.ok(await db.reservation.count({where:{claimId:o.orderId,state:"active"}}));});
